add metrics error

diff --git a/deploy/orioledb/templates/scripts.yaml b/deploy/orioledb/templates/scripts.yaml
--- a/deploy/orioledb/templates/scripts.yaml
+++ b/deploy/orioledb/templates/scripts.yaml
@@ -5,15 +5,6 @@ metadata:
   labels:
     {{- include "orioledb.labels" . | nindent 4 }}
 data:
-  init_container.sh: |
-    #!/bin/bash
-    set -o errexit
-    set -ex
-    mkdir -p /home/postgres/pgdata/conf
-    chmod 777 -R /home/postgres/pgdata/conf
-    cp /home/postgres/conf/postgresql.conf /home/postgres/pgdata/conf
-    chmod 777 /home/postgres/pgdata/conf/postgresql.conf
-
   generate_patroni_yaml.py: |
     #!/usr/bin/env python3
     # -*- coding: utf-8 -*-
@@ -76,55 +67,65 @@ data:
         write_file(yaml.dump(local_config, default_flow_style=False), filename, True)
     if __name__ == '__main__':
         main(sys.argv[1])
+  create_pg_stat_statements_extension.sql: |
+    CREATE EXTENSION pg_stat_statements;
   setup.sh: |
-    #!/bin/bash
-    set -o errexit
-    set -ex
+    cp /kb-scripts/create_pg_stat_statements_extension.sql /docker-entrypoint-initdb.d
+    bash /usr/local/bin/docker-entrypoint.sh postgres
+    su - postgres -c "postgres --hba_file=/home/postgres/conf/pg_hba.conf --config_file=/home/postgres/conf/postgresql.conf -D ${PGDATA}"
+{{/*    target_data_dir=/home/postgres/pgdata*/}}
+{{/*    ln -s $target_data_dir $PGDATA*/}}
+{{/*    su - postgres*/}}
+{{/*    postgres --config-file /var/lib/postgresql/data/pgdata/conf*/}}
+{{/*  sudo systemctl stop postgresql*/}}
+{{/*    #!/bin/bash*/}}
+{{/*    set -o errexit*/}}
+{{/*    set -ex*/}}
 
-    # Waiting for primary pod information from the DownwardAPI annotation to be available, with a maximum of 5 attempts
-    attempt=1
-    max_attempts=5
-    while [ $attempt -le $max_attempts ] && [ -z "$(cat /kb-podinfo/primary-pod)" ]; do
-      sleep 5
-      attempt=$((attempt + 1))
-    done
+{{/*    # Waiting for primary pod information from the DownwardAPI annotation to be available, with a maximum of 5 attempts*/}}
+{{/*    attempt=1*/}}
+{{/*    max_attempts=5*/}}
+{{/*    while [ $attempt -le $max_attempts ] && [ -z "$(cat /kb-podinfo/primary-pod)" ]; do*/}}
+{{/*      sleep 5*/}}
+{{/*      attempt=$((attempt + 1))*/}}
+{{/*    done*/}}
 
-    primary=$(cat /kb-podinfo/primary-pod)
-    echo "DownwardAPI get primary=$primary" >> /home/postgres/pgdata/.kb_set_up.log
-    echo "KB_POD_NAME=$KB_POD_NAME" >> /home/postgres/pgdata/.kb_set_up.log
-    if [ -z "$primary" ]; then
-      echo "Primary pod information not available. Exiting..."
-      exit 1
-    fi
+{{/*    primary=$(cat /kb-podinfo/primary-pod)*/}}
+{{/*    echo "DownwardAPI get primary=$primary" >> /home/postgres/pgdata/.kb_set_up.log*/}}
+{{/*    echo "KB_POD_NAME=$KB_POD_NAME" >> /home/postgres/pgdata/.kb_set_up.log*/}}
+{{/*    if [ -z "$primary" ]; then*/}}
+{{/*      echo "Primary pod information not available. Exiting..."*/}}
+{{/*      exit 1*/}}
+{{/*    fi*/}}
 
-    # usage: retry <command>
-    # e.g. retry pg_isready -U postgres -h $primary_fqdn -p 5432
-    function retry {
-      local max_attempts=10
-      local attempt=1
-      until "$@" || [ $attempt -eq $max_attempts ]; do
-        echo "Command '$*' failed. Attempt $attempt of $max_attempts. Retrying in 5 seconds..."
-        attempt=$((attempt + 1))
-        sleep 5
-      done
-      if [ $attempt -eq $max_attempts ]; then
-        echo "Command '$*' failed after $max_attempts attempts. Exiting..."
-        exit 1
-      fi
-    }
-    if [ "$primary" != "$KB_POD_NAME" ]; then
-        primary_fqdn="$primary.$KB_CLUSTER_NAME-$KB_COMP_NAME-headless.$KB_NAMESPACE.svc"
-        echo "primary_fqdn=$primary_fqdn" >> /home/postgres/pgdata/.kb_set_up.log
-        # waiting for the primary to be ready, if the wait time exceeds the maximum number of retries, then the script will fail and exit.
-        retry pg_isready -U {{ default "postgres" | quote }} -h $primary_fqdn -p 5432
-    fi
+{{/*    # usage: retry <command>*/}}
+{{/*    # e.g. retry pg_isready -U postgres -h $primary_fqdn -p 5432*/}}
+{{/*    function retry {*/}}
+{{/*      local max_attempts=10*/}}
+{{/*      local attempt=1*/}}
+{{/*      until "$@" || [ $attempt -eq $max_attempts ]; do*/}}
+{{/*        echo "Command '$*' failed. Attempt $attempt of $max_attempts. Retrying in 5 seconds..."*/}}
+{{/*        attempt=$((attempt + 1))*/}}
+{{/*        sleep 5*/}}
+{{/*      done*/}}
+{{/*      if [ $attempt -eq $max_attempts ]; then*/}}
+{{/*        echo "Command '$*' failed after $max_attempts attempts. Exiting..."*/}}
+{{/*        exit 1*/}}
+{{/*      fi*/}}
+{{/*    }*/}}
+{{/*    if [ "$primary" != "$KB_POD_NAME" ]; then*/}}
+{{/*        primary_fqdn="$primary.$KB_CLUSTER_NAME-$KB_COMP_NAME-headless.$KB_NAMESPACE.svc"*/}}
+{{/*        echo "primary_fqdn=$primary_fqdn" >> /home/postgres/pgdata/.kb_set_up.log*/}}
+{{/*        # waiting for the primary to be ready, if the wait time exceeds the maximum number of retries, then the script will fail and exit.*/}}
+{{/*        retry pg_isready -U {{ default "postgres" | quote }} -h $primary_fqdn -p 5432*/}}
+{{/*    fi*/}}
 
-    if [ -f ${RESTORE_DATA_DIR}/kb_restore.signal ]; then
-        chown -R postgres ${RESTORE_DATA_DIR}
-    fi
-    python3 /kb-scripts/generate_patroni_yaml.py tmp_patroni.yaml
-    export SPILO_CONFIGURATION=$(cat tmp_patroni.yaml)
-    exec /launch.sh init
+{{/*    if [ -f ${RESTORE_DATA_DIR}/kb_restore.signal ]; then*/}}
+{{/*        chown -R postgres ${RESTORE_DATA_DIR}*/}}
+{{/*    fi*/}}
+{{/*    python3 /kb-scripts/generate_patroni_yaml.py tmp_patroni.yaml*/}}
+{{/*    export SPILO_CONFIGURATION=$(cat tmp_patroni.yaml)*/}}
+    {{/*    exec /launch.sh init*/}}
   pgbouncer_setup.sh: |
     #!/bin/bash
     set -o errexit
