fix: improve setup scripts to tolerate timeout error (#1125)

diff --git a/deploy/wesql/templates/scripts.yaml b/deploy/wesql/templates/scripts.yaml
--- a/deploy/wesql/templates/scripts.yaml
+++ b/deploy/wesql/templates/scripts.yaml
@@ -26,25 +26,18 @@ data:
       if [ ! -z $MYSQL_ROOT_PASSWORD ]; then 
         password_flag="-p$MYSQL_ROOT_PASSWORD"
       fi
-      echo "mysql $host_flag -uroot $password_flag -e \"call dbms_consensus.add_follower('$host:13306');\" > /tmp/setup_error.log 2>&1 & "
-      mysql $host_flag -uroot $password_flag -e "call dbms_consensus.add_follower('$host:13306');" > /tmp/setup_error.log 2>&1 & 
-      # wait longer in case there's network issue
-      pid=$!; sleep 3;
-      ps $pid
-      if ! ps $pid > /dev/null; then 
-        wait $pid; 
-        code=$?; 
+      echo "mysql $host_flag -uroot $password_flag -e \"call dbms_consensus.add_learner('$host:13306');\" >> /tmp/setup_error.log 2>&1 "
+      mysql $host_flag -uroot $password_flag -e "call dbms_consensus.add_learner('$host:13306');" >> /tmp/setup_error.log 2>&1 
+      code=$?
+      echo "exit code: $code" 
+      if [ $code -ne 0 ]; then
         cat /tmp/setup_error.log
-        if [ $code -ne 0 ]; then
-          substr=`cat /tmp/setup_error.log | grep "Target node already exists"`
-          if [ -z "$substr" ]; then
-            exit $code; 
-          fi
+        already_exists=`cat /tmp/setup_error.log | grep "Target node already exists"`
+        if [ -z "$already_exists" ]; then 
+          exit $code
         fi
-      else 
-        echo "call dbms_consensus.add_follower stuck, which is normal during h-scale, skip."
-      fi
-      rm /tmp/setup_error.log
+      fi 
+      /scripts/upgrade-learner.sh &
     fi
     cluster_info=""; for (( i=0; i< $KB_MYSQL_N; i++ )); do
       if [ $i -ne 0 ]; then
@@ -73,3 +66,67 @@ data:
       echo "docker-entrypoint.sh mysqld --defaults-file=/opt/mysql/my.cnf --cluster-start-index=$CLUSTER_START_INDEX --cluster-info=\"$host:13306@1\" --cluster-id=$CLUSTER_ID"
       exec docker-entrypoint.sh mysqld --defaults-file=/opt/mysql/my.cnf --cluster-start-index=$CLUSTER_START_INDEX --cluster-info="$host:13306@1" --cluster-id=$CLUSTER_ID
     fi
+  upgrade-learner.sh: |
+    #!/bin/bash
+    leader=$KB_MYSQL_LEADER
+    idx=${KB_POD_NAME##*-}
+    host=$(eval echo \$KB_MYSQL_"$idx"_HOSTNAME)
+    leader_idx=${leader##*-}
+    leader_host=$(eval echo \$KB_MYSQL_"$leader_idx"_HOSTNAME)
+    if [ ! -z $leader_host ]; then 
+      host_flag="-h$leader_host"
+    fi
+    if [ ! -z $MYSQL_ROOT_PASSWORD ]; then 
+      password_flag="-p$MYSQL_ROOT_PASSWORD"
+    fi
+    while true
+    do
+      sleep 5
+      mysql -uroot $password_flag -e "select  ROLE  from information_schema.wesql_cluster_local" > /tmp/role.log 2>&1 &
+      pid=$!; sleep 2;
+      if ! ps $pid > /dev/null; then 
+        wait $pid; 
+        code=$?; 
+        if [ $code -ne 0 ]; then 
+          cat /tmp/role.log >> /tmp/upgrade-learner.log
+        else 
+          role=`cat /tmp/role.log`
+          echo "role: $role" >> /tmp/upgrade-learner.log
+          if [ -z "$role" ]; then 
+            echo "cannot get role" >> /tmp/upgrade-learner.log
+          else 
+            break
+          fi
+        fi
+      else 
+        kill -9 $pid
+        echo "mysql timeout" >> /tmp/upgrade-learner.log
+      fi
+    done
+    grep_learner=`echo $role | grep "Learner"`
+    echo "grep learner: $grep_learner" >> /tmp/upgrade-learner.log
+    if [ -z "$grep_learner" ]; then 
+      exit 0
+    fi
+    while true
+    do 
+      mysql $host_flag -uroot $password_flag -e "call dbms_consensus.upgrade_learner('$host:13306');" >> /tmp/upgrade.log 2>&1 &
+      pid=$!; sleep 2;
+      if ! ps $pid > /dev/null; then 
+        wait $pid; 
+        code=$?; 
+        if [ $code -ne 0 ]; then 
+          cat /tmp/upgrade.log >> /tmp/upgrade-learner.log
+          already_exists=`cat /tmp/upgrade.log | grep "Target node already exists"`
+          if [ ! -z "$already_exists" ]; then 
+            break
+          fi 
+        else 
+          break
+        fi
+      else 
+        kill -9 $pid
+        echo "mysql call leader timeout" >> /tmp/upgrade-learner.log
+      fi
+      sleep 5
+    done
