chore: release image kubeblocks-dataprotection

diff --git a/.github/workflows/cicd-pull-request.yml b/.github/workflows/cicd-pull-request.yml
--- a/.github/workflows/cicd-pull-request.yml
+++ b/.github/workflows/cicd-pull-request.yml
@@ -174,6 +174,16 @@ jobs:
       DOCKERFILE_PATH: "./docker/Dockerfile-datascript"
     secrets: inherit
 
+  check-dataprotection-image:
+    needs: trigger-mode
+    if: contains(needs.trigger-mode.outputs.trigger-mode, '[docker]')
+    uses: apecloud/apecloud-cd/.github/workflows/release-image-check.yml@v0.1.12
+    with:
+      IMG: "apecloud/kubeblocks-dataprotection"
+      BUILDX_PLATFORMS: "linux/amd64"
+      DOCKERFILE_PATH: "./docker/Dockerfile-dataprotection"
+    secrets: inherit
+
   check-helm:
     name: check helm
     needs: trigger-mode
@@ -222,7 +232,7 @@ jobs:
 
   pr-check:
     name: make test
-    needs: [ trigger-mode, test-parallel, make-test, check-image, check-tools-image, check-datascript-image, check-helm, check-kbcli ]
+    needs: [ trigger-mode, test-parallel, make-test, check-image, check-tools-image, check-datascript-image, check-dataprotection-image, check-helm, check-kbcli ]
     if: ${{ github.event.review.state == 'approved' && always() }}
     runs-on: ubuntu-latest
     steps:
@@ -256,6 +266,11 @@ jobs:
 
           if [[ "${{ needs.check-datascript-image.result }}" == "failure" || "${{ needs.check-datascript-image.result }}" == "cancelled" ]]; then
               echo "release datascript image fail"
+              exit 1
+          fi
+
+          if [[ "${{ needs.check-dataprotection-image.result }}" == "failure" || "${{ needs.check-dataprotection-image.result }}" == "cancelled" ]]; then
+              echo "release dataprotection image fail"
               exit 1
           fi
 
