chore: upload coverage fork pr (#4138)

diff --git a/.github/workflows/cicd-pull-request.yml b/.github/workflows/cicd-pull-request.yml
--- a/.github/workflows/cicd-pull-request.yml
+++ b/.github/workflows/cicd-pull-request.yml
@@ -24,16 +24,10 @@ jobs:
           access_token: ${{ github.token }}
 
       - uses: actions/checkout@v3
-        if: github.event.pull_request.head.repo.full_name == github.repository
-        with:
-          fetch-depth: 0     
-
-      - uses: actions/checkout@v3
-        if: github.event.pull_request.head.repo.full_name != github.repository
         with:
           fetch-depth: 0
           repository: ${{ github.event.pull_request.head.repo.full_name }}
-      
+
       - name: Get trigger mode
         id: get_trigger_mode
         run: |
@@ -52,9 +46,9 @@ jobs:
           echo "matrix={\"include\":[$TEST_PACKAGES]}" >> $GITHUB_OUTPUT
 
   test-parallel:
-    name: make test
+    name: test
     needs: trigger-mode
-    if: contains(needs.trigger-mode.outputs.trigger-mode, '[test]')
+    if: ${{ contains(needs.trigger-mode.outputs.trigger-mode, '[test]') && github.event.pull_request.head.repo.full_name == github.repository }}
     runs-on: ubuntu-latest
     strategy:
       fail-fast: true
@@ -89,17 +83,62 @@ jobs:
           make test TEST_PACKAGES=./${{ matrix.ops }}/...
 
   make-test:
-    name: make test
-    needs: [ trigger-mode, test-parallel ]
-    if: ${{ contains(needs.trigger-mode.outputs.trigger-mode, '[test]') && always() }}
-    runs-on: ubuntu-latest
+    needs: trigger-mode
+    if: ${{ contains(needs.trigger-mode.outputs.trigger-mode, '[test]') && github.event.pull_request.head.repo.full_name != github.repository }}
+    outputs:
+      runner-name: ${{ steps.get_runner_name.outputs.runner_name }}
+    runs-on: [ self-hosted, kubeblocks-runner ]
     steps:
-      - name: make test check
+      - uses: actions/checkout@v3
+      - name: make mod-vendor
         run: |
-          if [[ "${{ needs.test-parallel.result }}" == "failure" || "${{ needs.test-parallel.result }}" == "cancelled" ]]; then
-              echo "make test fail"
-              exit 1
-          fi
+          mkdir -p ./bin
+          cp -r /go/bin/controller-gen ./bin/controller-gen
+          cp -r /go/bin/setup-envtest ./bin/setup-envtest
+          make mod-vendor
+
+      - name: make lint
+        run: |
+          make lint
+
+      - name: make test
+        run: |
+          make test
+
+      - name: ignore cover pkgs
+        run: |
+          bash .github/utils/utils.sh --type 14 \
+              --file cover.out \
+              --ignore-pkgs "cmd/|internal/cli|internal/controller/consensusset|internal/controller/model|controllers/k8score" 
+
+      - name: upload coverage report
+        uses: codecov/codecov-action@v3
+        continue-on-error: true
+        with:
+          token: ${{ secrets.CODECOV_TOKEN }}
+          files: ./cover_new.out
+          flags: unittests
+          name: codecov-report
+          verbose: true
+
+      - name: kill kube-apiserver and etcd
+        id: get_runner_name
+        if: ${{ always() }}
+        run: |
+          echo runner_name=${RUNNER_NAME} >> $GITHUB_OUTPUT
+          bash .github/utils/utils.sh --type 8
+
+  remove-runner:
+    needs: [ trigger-mode, make-test ]
+    runs-on: ubuntu-latest
+    if: ${{ contains(needs.trigger-mode.outputs.trigger-mode, '[test]') && github.event.pull_request.head.repo.full_name != github.repository && always()  }}
+    steps:
+      - uses: actions/checkout@v3
+      - name: remove runner
+        run: |
+          bash .github/utils/utils.sh --type 9 \
+              --github-token ${{ env.GITHUB_TOKEN }} \
+              --runner-name ${{ needs.make-test.outputs.runner-name }}
 
   check-image:
     name: check image
@@ -144,3 +183,44 @@ jobs:
       DEP_REPO: "delphic|prometheus-cluster|apecloud-mysql-cluster|tdengine-cluster"
       APECD_REF: "v0.1.4"
     secrets: inherit
+
+  pr-check:
+    name: make test
+    needs: [ test-parallel, make-test, check-image, check-tools-image, check-helm ]
+    if: ${{ always() }}
+    runs-on: ubuntu-latest
+    steps:
+      - name: test parallel check
+        if: github.event.pull_request.head.repo.full_name == github.repository
+        run: |
+          if [[ "${{ needs.test-parallel.result }}" == "failure" || "${{ needs.test-parallel.result }}" == "cancelled" ]]; then
+              echo "test parallel fail"
+              exit 1
+          fi
+
+      - name: make test check
+        if: github.event.pull_request.head.repo.full_name != github.repository
+        run: |
+          if [[ "${{ needs.make-test.result }}" == "failure" || "${{ needs.make-test.result }}" == "cancelled" ]]; then
+              echo "make test fail"
+              exit 1
+          fi
+
+      - name: release image check
+        run: |
+          if [[ "${{ needs.check-image.result }}" == "failure" || "${{ needs.check-image.result }}" == "cancelled" ]]; then
+              echo "release image fail"
+              exit 1
+          fi
+          
+          if [[ "${{ needs.check-tools-image.result }}" == "failure" || "${{ needs.check-tools-image.result }}" == "cancelled" ]]; then
+              echo "release tools image fail"
+              exit 1
+          fi
+
+      - name: release helm check
+        run: |
+          if [[ "${{ needs.check-helm.result }}" == "failure" || "${{ needs.check-helm.result }}" == "cancelled" ]]; then
+              echo "release helm fail"
+              exit 1
+          fi
