chore: cherry pick cicd workflow optimize (#7980)

diff --git a/.github/workflows/cicd-pull-request.yml b/.github/workflows/cicd-pull-request.yml
--- a/.github/workflows/cicd-pull-request.yml
+++ b/.github/workflows/cicd-pull-request.yml
@@ -1,8 +1,11 @@
-name: CICD-PULL-REQUEST
+name: Pull Request
 
 on:
-  pull_request_review:
-    types: [submitted]
+  pull_request:
+    types: [ labeled ]
+    branches:
+      - main
+      - release-*
 
 env:
   GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
@@ -12,7 +15,7 @@ env:
 jobs:
   trigger-mode:
     name: trigger mode
-    if: github.event.review.state == 'approved'
+    if: github.event.action == 'labeled' && (github.event.label.name == 'approved' || github.event.label.name == 'pre-approve')
     runs-on: ubuntu-latest
     outputs:
       trigger-mode: ${{ steps.get_trigger_mode.outputs.trigger_mode }}
@@ -74,6 +77,7 @@ jobs:
       - uses: actions/checkout@v4
       - name: install lib
         run: |
+          sudo rm /etc/apt/sources.list.d/microsoft-prod.list
           sudo apt-get update
           sudo apt-get install -y --no-install-recommends \
             libbtrfs-dev \
@@ -101,7 +105,45 @@ jobs:
               make test TEST_PACKAGES=./${{ matrix.ops }}/...
           fi
 
-  make-test:
+  pr-pre-check:
+    needs: trigger-mode
+    if: ${{ contains(needs.trigger-mode.outputs.trigger-mode, '[test]') && github.event.pull_request.head.repo.full_name != github.repository }}
+    runs-on: ubuntu-latest
+    strategy:
+      fail-fast: true
+      matrix:
+        ops: [ 'manifests', 'mod-vendor', 'generate', 'lint', 'staticcheck' ]
+    steps:
+      - uses: actions/checkout@v4
+      - name: install lib
+        run: |
+          sudo rm /etc/apt/sources.list.d/microsoft-prod.list
+          sudo apt-get update
+          sudo apt-get install -y --no-install-recommends \
+            libbtrfs-dev \
+            libdevmapper-dev
+
+      - name: Set up Go
+        uses: actions/setup-go@v4
+        with:
+          go-version: "${{ env.GO_VERSION }}"
+
+      - name: Install golangci-lint
+        if: matrix.ops == 'lint'
+        run: |
+          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.55.2
+
+      - name: make ${{ matrix.ops }}
+        run: |
+          make ${{ matrix.ops }}
+          FILE_CHANGES=`git diff --name-only ${{ github.sha }}`
+          if [[ ("${{ matrix.ops }}" == 'generate' || "${{ matrix.ops }}" == 'manifests') && -n "$FILE_CHANGES" ]]; then
+              echo $FILE_CHANGES
+              echo "make "${{ matrix.ops }}" causes inconsistent files"
+              exit 1
+          fi
+
+  pr-make-test:
     needs: trigger-mode
     if: ${{ contains(needs.trigger-mode.outputs.trigger-mode, '[test]') && github.event.pull_request.head.repo.full_name != github.repository }}
     outputs:
@@ -109,14 +151,6 @@ jobs:
     runs-on: [ self-hosted, gke-runner-go1.21 ]
     steps:
       - uses: actions/checkout@v4
-      - name: make mod-vendor
-        run: |
-          make mod-vendor
-
-      - name: make lint
-        run: |
-          make lint
-
       - name: make test
         run: |
           make test
@@ -145,7 +179,7 @@ jobs:
           bash .github/utils/utils.sh --type 8
 
   remove-runner:
-    needs: [ trigger-mode, make-test ]
+    needs: [ trigger-mode, pr-make-test ]
     runs-on: ubuntu-latest
     if: ${{ contains(needs.trigger-mode.outputs.trigger-mode, '[test]') && github.event.pull_request.head.repo.full_name != github.repository && always()  }}
     steps:
@@ -154,7 +188,7 @@ jobs:
         run: |
           bash .github/utils/utils.sh --type 9 \
               --github-token ${{ env.GITHUB_TOKEN }} \
-              --runner-name ${{ needs.make-test.outputs.runner-name }}
+              --runner-name ${{ needs.pr-make-test.outputs.runner-name }}
 
   check-image:
     needs: trigger-mode
@@ -221,8 +255,9 @@ jobs:
 
   pr-check:
     name: make test
-    needs: [ trigger-mode, test-parallel, make-test, check-image, check-tools-image, check-datascript-image, check-dataprotection-image, check-helm ]
-    if: ${{ github.event.review.state == 'approved' && always() }}
+    needs: [ trigger-mode, test-parallel, pr-pre-check, pr-make-test,
+             check-image, check-tools-image, check-datascript-image, check-dataprotection-image, check-helm ]
+    if: ${{ github.event.action == 'labeled' && (github.event.label.name == 'approved' || github.event.label.name == 'pre-approve') && always() }}
     runs-on: ubuntu-latest
     steps:
       - name: test parallel check
@@ -233,10 +268,18 @@ jobs:
               exit 1
           fi
 
+      - name: pr pre check
+        if: github.event.pull_request.head.repo.full_name != github.repository
+        run: |
+          if [[ "${{ needs.pr-pre-check.result }}" == "failure" || "${{ needs.pr-pre-check.result }}" == "cancelled" ]]; then
+              echo "make test fail"
+              exit 1
+          fi
+
       - name: make test check
         if: github.event.pull_request.head.repo.full_name != github.repository
         run: |
-          if [[ "${{ needs.make-test.result }}" == "failure" || "${{ needs.make-test.result }}" == "cancelled" ]]; then
+          if [[ "${{ needs.pr-make-test.result }}" == "failure" || "${{ needs.pr-make-test.result }}" == "cancelled" ]]; then
               echo "make test fail"
               exit 1
           fi
diff --git a/.github/workflows/cicd-push.yml b/.github/workflows/cicd-push.yml
--- a/.github/workflows/cicd-push.yml
+++ b/.github/workflows/cicd-push.yml
@@ -1,4 +1,4 @@
-name: CICD-PUSH
+name: CICD Push
 
 on:
   push:
@@ -73,6 +73,7 @@ jobs:
           fetch-depth: 0
       - name: install pcregrep
         run: |
+          sudo rm /etc/apt/sources.list.d/microsoft-prod.list
           sudo apt-get update
           sudo apt-get install pcregrep
 
@@ -98,7 +99,45 @@ jobs:
           files: docs/
           config: .github/utils/typos.toml
 
-  make-test:
+  push-pre-check:
+    needs: trigger-mode
+    if: contains(needs.trigger-mode.outputs.trigger-mode, '[test]')
+    runs-on: ubuntu-latest
+    strategy:
+      fail-fast: true
+      matrix:
+        ops: [ 'manifests', 'mod-vendor', 'generate', 'lint', 'staticcheck' ]
+    steps:
+      - uses: actions/checkout@v4
+      - name: install lib
+        run: |
+          sudo rm /etc/apt/sources.list.d/microsoft-prod.list
+          sudo apt-get update
+          sudo apt-get install -y --no-install-recommends \
+            libbtrfs-dev \
+            libdevmapper-dev
+
+      - name: Set up Go
+        uses: actions/setup-go@v4
+        with:
+          go-version: "${{ env.GO_VERSION }}"
+
+      - name: Install golangci-lint
+        if: matrix.ops == 'lint'
+        run: |
+          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.55.2
+
+      - name: make ${{ matrix.ops }}
+        run: |
+          make ${{ matrix.ops }}
+          FILE_CHANGES=`git diff --name-only ${{ github.sha }}`
+          if [[ ("${{ matrix.ops }}" == 'generate' || "${{ matrix.ops }}" == 'manifests') && -n "$FILE_CHANGES" ]]; then
+              echo $FILE_CHANGES
+              echo "make "${{ matrix.ops }}" causes inconsistent files"
+              exit 1
+          fi
+
+  push-make-test:
     needs: trigger-mode
     runs-on: [self-hosted, gke-runner-go1.21]
     if: contains(needs.trigger-mode.outputs.trigger-mode, '[test]')
@@ -106,38 +145,6 @@ jobs:
       runner-name: ${{ steps.get_runner_name.outputs.runner_name }}
     steps:
       - uses: actions/checkout@v4
-      - name: make manifests check
-        run: |
-          make manifests
-          FILE_CHANGES=`git diff --name-only ${{ github.sha }}`
-          if [[ ! -z "$FILE_CHANGES" ]]; then
-            echo $FILE_CHANGES
-            echo "make manifests causes inconsistent files"
-            exit 1
-          fi
-
-      - name: make generate check
-        run: |
-          make generate
-          FILE_CHANGES=`git diff --name-only ${{ github.sha }}`
-          if [[ ! -z "$FILE_CHANGES" ]]; then
-            echo $FILE_CHANGES
-            echo "make generate causes inconsistent files"
-            exit 1
-          fi
-
-      - name: make mod-vendor
-        run: |
-          make mod-vendor
-
-      - name: make staticcheck
-        run: |
-          make staticcheck
-
-      - name: make lint
-        run: |
-          make lint
-
       - name: make test
         run: |
           make test
@@ -166,7 +173,7 @@ jobs:
           bash .github/utils/utils.sh --type 8
 
   remove-runner:
-    needs: [ trigger-mode, make-test ]
+    needs: [ trigger-mode, push-make-test ]
     runs-on: ubuntu-latest
     if: ${{ contains(needs.trigger-mode.outputs.trigger-mode, '[test]') && always() }}
     steps:
@@ -175,7 +182,7 @@ jobs:
         run: |
           bash .github/utils/utils.sh --type 9 \
             --github-token "${{ env.GITHUB_TOKEN }}" \
-            --runner-name ${{ needs.make-test.outputs.runner-name }}
+            --runner-name ${{ needs.push-make-test.outputs.runner-name }}
 
   check-image:
     needs: trigger-mode
@@ -269,6 +276,7 @@ jobs:
       - uses: actions/checkout@v4
       - name: install lib
         run: |
+          sudo rm /etc/apt/sources.list.d/microsoft-prod.list
           sudo apt-get update
           sudo apt-get install -y --no-install-recommends \
             libbtrfs-dev \
@@ -301,4 +309,61 @@ jobs:
             echo "$check_lh_ret"
             echo "check license-header FAIL"
             exit 1
+          fi
+
+  push-check:
+    name: make-test
+    needs: [ trigger-mode, push-pre-check, push-make-test, check-image, check-tools-image,
+             check-datascript-image, check-dataprotection-image, check-helm, apis-doc, check-license-header ]
+    if: ${{ always() }}
+    runs-on: ubuntu-latest
+    steps:
+      - name: push pre check
+        run: |
+          if [[ "${{ needs.push-pre-check.result }}" == "failure" || "${{ needs.push-pre-check.result }}" == "cancelled" ]]; then
+              echo "push pre check fail"
+              exit 1
+          fi
+
+      - name: make test check
+        run: |
+          if [[ "${{ needs.push-make-test.result }}" == "failure" || "${{ needs.push-make-test.result }}" == "cancelled" ]]; then
+              echo "make test fail"
+              exit 1
+          fi
+
+      - name: release image check
+        run: |
+          if [[ "${{ needs.check-image.result }}" == "failure" || "${{ needs.check-image.result }}" == "cancelled" ]]; then
+              echo "check kubeblocks image fail"
+              exit 1
+          fi
+
+          if [[ "${{ needs.check-tools-image.result }}" == "failure" || "${{ needs.check-tools-image.result }}" == "cancelled" ]]; then
+              echo "check tools image fail"
+              exit 1
+          fi
+
+          if [[ "${{ needs.check-datascript-image.result }}" == "failure" || "${{ needs.check-datascript-image.result }}" == "cancelled" ]]; then
+              echo "check datascript image fail"
+              exit 1
+          fi
+
+          if [[ "${{ needs.check-dataprotection-image.result }}" == "failure" || "${{ needs.check-dataprotection-image.result }}" == "cancelled" ]]; then
+              echo "check dataprotection image fail"
+              exit 1
+          fi
+
+      - name: apis doc check
+        run: |
+          if [[ "${{ needs.check-license-header.result }}" == "failure" || "${{ needs.check-license-header.result }}" == "cancelled" ]]; then
+              echo "check apis doc fail"
+              exit 1
+          fi
+
+      - name: license header check
+        run: |
+          if [[ "${{ needs.check-license-header.result }}" == "failure" || "${{ needs.check-license-header.result }}" == "cancelled" ]]; then
+              echo "check license header fail"
+              exit 1
           fi
