test

diff --git a/.github/workflows/release-publish.yml b/.github/workflows/release-publish.yml
--- a/.github/workflows/release-publish.yml
+++ b/.github/workflows/release-publish.yml
@@ -1,8 +1,10 @@
 name: RELEASE-PUBLISH
 
 on:
+#  workflow_dispatch:
   release:
     types:
+      - push
       - published
 
 permissions:
@@ -11,7 +13,8 @@ permissions:
 env:
   GH_TOKEN: ${{ github.token }}
   GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
-  TAG_NAME: ${{ github.ref_name }}
+#  TAG_NAME: ${{ github.ref_name }}
+  TAG_NAME: "test-for-windows"
   GO_VERSION: "1.20"
   CLI_NAME: 'kbcli'
   CLI_REPO: 'apecloud/kbcli'
@@ -38,13 +41,13 @@ jobs:
           repository: ${{ env.CLI_REPO }}
           token: ${{ env.GITHUB_TOKEN }}
           prerelease: true
-      - name: create gitlab release ${{ env.CLI_NAME }}
-        run: |
-          bash ${{ github.workspace }}/.github/utils/release_gitlab.sh \
-            --type 1 \
-            --project-id ${{ env.GITLAB_KBCLI_PROJECT_ID }} \
-            --tag-name ${{ env.TAG_NAME }} \
-            --access-token ${{ env.GITLAB_ACCESS_TOKEN }}
+#      - name: create gitlab release ${{ env.CLI_NAME }}
+#        run: |
+#          bash ${{ github.workspace }}/.github/utils/release_gitlab.sh \
+#            --type 1 \
+#            --project-id ${{ env.GITLAB_KBCLI_PROJECT_ID }} \
+#            --tag-name ${{ env.TAG_NAME }} \
+#            --access-token ${{ env.GITLAB_ACCESS_TOKEN }}
 
   gorelease-assert:
     needs: create-release-kbcli
@@ -81,12 +84,12 @@ jobs:
           GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
           GPG_FINGERPRINT: ${{ steps.import_gpg.outputs.fingerprint }}
 
-      - name: upload .rpm and .deb to fury.io
-        run: |
-          for file in $(find "${{ github.workspace }}/dist" -type f | grep -E '\.(deb|rpm)$'); do
-            echo "Processing file: $file"
-            curl -F package=@$file https://${{ env.FURY_TOKEN }}@push.fury.io/${{ env.FURY_ACCOUNT }}/
-          done
+#      - name: upload .rpm and .deb to fury.io
+#        run: |
+#          for file in $(find "${{ github.workspace }}/dist" -type f | grep -E '\.(deb|rpm)$'); do
+#            echo "Processing file: $file"
+#            curl -F package=@$file https://${{ env.FURY_TOKEN }}@push.fury.io/${{ env.FURY_ACCOUNT }}/
+#          done
 
       - name: get kbcli's release upload url
         run: |
@@ -128,7 +131,8 @@ jobs:
     strategy:
       fail-fast: false
       matrix:
-        os: [linux-amd64, linux-arm64, darwin-amd64, darwin-arm64, windows-amd64, windows-arm64]
+#        os: [linux-amd64, linux-arm64, darwin-amd64, darwin-arm64, windows-amd64, windows-arm64]
+        os: [lindows-amd64]
     steps:
       - uses: actions/checkout@v3
       - name: Download kbcli Artifact
@@ -137,21 +141,21 @@ jobs:
           name: ${{ env.TAG_NAME }}-kbcli
           path: ${{ github.workspace }}/dist
 
-      - name: upload assets to gitlab
-        run: |
-          for file in $(find "${{ github.workspace }}/dist" -type f | grep -E '\.(gz|zip)$'); do
-              if [[ "$file" == *"${{ matrix.os }}"* ]]; then
-                  echo "Processing file: $file"
-                  filename=$(basename "$file")
-                  bash ${{ github.workspace }}/.github/utils/release_gitlab.sh \
-                  --type 2 \
-                  --project-id ${{ env.GITLAB_KBCLI_PROJECT_ID }} \
-                  --tag-name ${{ env.TAG_NAME }} \
-                  --asset-path $file \
-                  --asset-name $filename \
-                  --access-token ${{ env.GITLAB_ACCESS_TOKEN }}
-              fi
-          done
+#      - name: upload assets to gitlab
+#        run: |
+#          for file in $(find "${{ github.workspace }}/dist" -type f | grep -E '\.(gz|zip)$'); do
+#              if [[ "$file" == *"${{ matrix.os }}"* ]]; then
+#                  echo "Processing file: $file"
+#                  filename=$(basename "$file")
+#                  bash ${{ github.workspace }}/.github/utils/release_gitlab.sh \
+#                  --type 2 \
+#                  --project-id ${{ env.GITLAB_KBCLI_PROJECT_ID }} \
+#                  --tag-name ${{ env.TAG_NAME }} \
+#                  --asset-path $file \
+#                  --asset-name $filename \
+#                  --access-token ${{ env.GITLAB_ACCESS_TOKEN }}
+#              fi
+#          done
 
   remove-artifact:
     needs: upload-release-assert
@@ -162,93 +166,93 @@ jobs:
         with:
           name: ${{ env.TAG_NAME }}-kbcli
 
-  send-message:
-    runs-on: ubuntu-latest
-    needs: upload-release-assert
-    outputs:
-      tag-name: ${{ steps.send_message.outputs.tag_name }}
-    if: ${{ always() && github.event.action == 'published' }}
-    steps:
-      - uses: actions/checkout@v3
-      - name: send message
-        id: send_message
-        run: |
-          release_result="${{ env.TAG_NAME }}-kbcli"
-          touch ${release_result}
-          echo 'release-result='${release_result} >> $GITHUB_OUTPUT
-          
-          CONTENT="release\u00a0${{ env.TAG_NAME }}\u00a0kbcli\u00a0error"
-          if [[ "${{ needs.upload-release-assert.result }}" == "success" ]]; then
-              CONTENT="release\u00a0${{ env.TAG_NAME }}\u00a0kbcli\u00a0success"
-              echo "success" > ${release_result}
-          else
-              echo "error" > ${release_result}
-          fi
-          
-          bash .github/utils/utils.sh --type 12 \
-            --tag-name ${{ env.TAG_NAME }} \
-            --content "${CONTENT}"\
-            --bot-webhook ${{ env.RELEASE_BOT_WEBHOOK }} \
-            --run-url "$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"
-          
-          echo tag_name=${{ env.TAG_NAME }} >> $GITHUB_OUTPUT
-
-      - name: delete cache
-        continue-on-error: true
-        run: |
-          bash .github/utils/utils.sh --type 17 --tag-name "${{ steps.send_message.outputs.release-result }}"
-
-      - name: Save Artifact
-        id: cache-artifact-save
-        uses: actions/cache/save@v3
-        with:
-          path: |
-            ${{ steps.send_message.outputs.release-result }}
-          key: ${{ steps.send_message.outputs.release-result }}
-
-  release-result:
-    if: github.event.action == 'published'
-    needs: [ send-message ]
-    runs-on: ubuntu-latest
-    strategy:
-      matrix:
-        type: [image, kbcli, chart]
-    steps:
-      - name: Restore ${{ matrix.type }} Artifact
-        id: cache-artifact-restore
-        uses: actions/cache/restore@v3
-        with:
-          path: |
-            ${{ env.TAG_NAME }}-${{ matrix.type }}
-          key: ${{ env.TAG_NAME }}-${{ matrix.type }}
-
-      - name: check release result
-        run: |
-          release_result=$( cat ${{ env.TAG_NAME }}-${{ matrix.type }} )
-          if [[ "$release_result" != "success" ]]; then
-              exit 1
-          fi
-
-  e2e-kbcli:
-    needs: [ send-message, release-result ]
-    uses: apecloud/apecloud-cd/.github/workflows/trigger-workflow.yml@v0.1.4
-    with:
-      GITHUB_REPO: "apecloud/kubeblocks"
-      BRANCH_NAME: "main"
-      WORKFLOW_ID: "e2e-kbcli.yml"
-      APECD_REF: "v0.1.4"
-      VERSION: "${{ needs.send-message.outputs.tag-name }}"
-    secrets: inherit
-
-  delete-cache:
-    needs: e2e-kbcli
-    runs-on: ubuntu-latest
-    strategy:
-      matrix:
-        type: [image, kbcli, chart]
-    steps:
-      - uses: actions/checkout@v3
-      - name: delete ${{ matrix.type }} cache
-        continue-on-error: true
-        run: |
-          bash .github/utils/utils.sh --type 17 --tag-name "${{ env.TAG_NAME }}-${{ matrix.type }}"
+#  send-message:
+#    runs-on: ubuntu-latest
+#    needs: upload-release-assert
+#    outputs:
+#      tag-name: ${{ steps.send_message.outputs.tag_name }}
+#    if: ${{ always() && github.event.action == 'published' }}
+#    steps:
+#      - uses: actions/checkout@v3
+#      - name: send message
+#        id: send_message
+#        run: |
+#          release_result="${{ env.TAG_NAME }}-kbcli"
+#          touch ${release_result}
+#          echo 'release-result='${release_result} >> $GITHUB_OUTPUT
+#
+#          CONTENT="release\u00a0${{ env.TAG_NAME }}\u00a0kbcli\u00a0error"
+#          if [[ "${{ needs.upload-release-assert.result }}" == "success" ]]; then
+#              CONTENT="release\u00a0${{ env.TAG_NAME }}\u00a0kbcli\u00a0success"
+#              echo "success" > ${release_result}
+#          else
+#              echo "error" > ${release_result}
+#          fi
+#
+#          bash .github/utils/utils.sh --type 12 \
+#            --tag-name ${{ env.TAG_NAME }} \
+#            --content "${CONTENT}"\
+#            --bot-webhook ${{ env.RELEASE_BOT_WEBHOOK }} \
+#            --run-url "$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"
+#
+#          echo tag_name=${{ env.TAG_NAME }} >> $GITHUB_OUTPUT
+#
+#      - name: delete cache
+#        continue-on-error: true
+#        run: |
+#          bash .github/utils/utils.sh --type 17 --tag-name "${{ steps.send_message.outputs.release-result }}"
+#
+#      - name: Save Artifact
+#        id: cache-artifact-save
+#        uses: actions/cache/save@v3
+#        with:
+#          path: |
+#            ${{ steps.send_message.outputs.release-result }}
+#          key: ${{ steps.send_message.outputs.release-result }}
+#
+#  release-result:
+#    if: github.event.action == 'published'
+#    needs: [ send-message ]
+#    runs-on: ubuntu-latest
+#    strategy:
+#      matrix:
+#        type: [image, kbcli, chart]
+#    steps:
+#      - name: Restore ${{ matrix.type }} Artifact
+#        id: cache-artifact-restore
+#        uses: actions/cache/restore@v3
+#        with:
+#          path: |
+#            ${{ env.TAG_NAME }}-${{ matrix.type }}
+#          key: ${{ env.TAG_NAME }}-${{ matrix.type }}
+#
+#      - name: check release result
+#        run: |
+#          release_result=$( cat ${{ env.TAG_NAME }}-${{ matrix.type }} )
+#          if [[ "$release_result" != "success" ]]; then
+#              exit 1
+#          fi
+#
+#  e2e-kbcli:
+#    needs: [ send-message, release-result ]
+#    uses: apecloud/apecloud-cd/.github/workflows/trigger-workflow.yml@v0.1.4
+#    with:
+#      GITHUB_REPO: "apecloud/kubeblocks"
+#      BRANCH_NAME: "main"
+#      WORKFLOW_ID: "e2e-kbcli.yml"
+#      APECD_REF: "v0.1.4"
+#      VERSION: "${{ needs.send-message.outputs.tag-name }}"
+#    secrets: inherit
+#
+#  delete-cache:
+#    needs: e2e-kbcli
+#    runs-on: ubuntu-latest
+#    strategy:
+#      matrix:
+#        type: [image, kbcli, chart]
+#    steps:
+#      - uses: actions/checkout@v3
+#      - name: delete ${{ matrix.type }} cache
+#        continue-on-error: true
+#        run: |
+#          bash .github/utils/utils.sh --type 17 --tag-name "${{ env.TAG_NAME }}-${{ matrix.type }}"
